apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-status-alerts
  namespace: monitoring
  labels:
    prometheus: prometheus
    role: alert-rules
spec:
  groups:
    - name: pod-health.rules
      rules:
        # ----------------------------------
        # Pod crash looping (noise-reduced)
        # ----------------------------------
        - alert: PodCrashLooping
          expr: |
            sum by (namespace, pod, container) (
              rate(kube_pod_container_status_restarts_total[10m])
            ) > 0.1
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Pod {{ $labels.pod }} is crash looping"
            description: |
              Container {{ $labels.container }} in pod {{ $labels.pod }}
              (namespace {{ $labels.namespace }}) is restarting frequently.

        # ----------------------------------
        # Image pull failures (covers both states)
        # ----------------------------------
        - alert: PodImagePullBackOff
          expr: |
            kube_pod_container_status_waiting_reason{
              reason=~"ImagePullBackOff|ErrImagePull"
            } > 0
          for: 3m
          labels:
            severity: critical
          annotations:
            summary: "Image pull failure for pod {{ $labels.pod }}"
            description: |
              Pod {{ $labels.pod }} in namespace {{ $labels.namespace }}
              cannot pull its container image.

        # ----------------------------------
        # OOM killed pods (real signal)
        # ----------------------------------
        - alert: PodOOMKilled
          expr: |
            kube_pod_container_status_terminated_reason{
              reason="OOMKilled"
            } > 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Pod {{ $labels.pod }} was OOMKilled"
            description: |
              Pod {{ $labels.pod }} in namespace {{ $labels.namespace }}
              was killed due to memory exhaustion.
