apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: trivy-vulnerability-alerts
  namespace: monitoring
  labels:
    prometheus: kube-prometheus-stack
    role: alert-rules
spec:
  groups:
    - name: trivy.security
      interval: 5m
      rules:
        - alert: TrivyCriticalVulnerabilityDetected
          expr: |
            trivy_operator_vulnerabilities_total{severity="CRITICAL"} > 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Critical container vulnerability detected"
            description: >
              One or more running containers have CRITICAL vulnerabilities.
              Immediate remediation is required.
