apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: penumbra-node
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:radiantcommons/rc-gitops.git'
    targetRevision: dev
    path: 'shared/charts/penumbra-node-helm'
    helm:
      releaseName: penumbra-node
      valueFiles:
        - ../../config/rc-appset/values-penumbra-node-helm.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: penumbra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
