apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cosmos-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/strangelove-ventures/cosmos-operator.git'
    targetRevision: main
    path: config/default
  destination:
    server: https://kubernetes.default.svc
    namespace: cosmos-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
