apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-provisioners
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:gabriel-devops-portfolio/gitops-apps.git"
    targetRevision: main
    path: "prod/karpenter"
    directory:
      recurse: false
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
