apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-resource
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:gabriel-devops-portfolio/gitops-apps.git"
    targetRevision: main
    path: "prod/api-gateways"
    directory:
      recurse: false
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
