apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rc-appset-ovh
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'git@github.com:radiantcommons/rc-gitops.git'
        revision: dev
        files:
          - path: 'ovh/config/rc-appset/*.yaml'
  template:
    metadata:
      annotations:
        notifications.argoproj.io/subscribe.on-sync-failed.slack: '{{ channel }}'
      name: '{{ application }}'
    spec:
      destination:
        namespace: '{{ clusterConfig.namespace }}'
        server: https://kubernetes.default.svc
      project: 'default'
      source:
        repoURL: git@github.com:radiantcommons/rc-gitops.git
        targetRevision: dev
        path: 'charts/{{ application }}'
        helm:
          valueFiles:
            - ../../ovh/config/rc-appset/values-{{ application }}.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
