apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sg-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:radiantcommons/rc-gitops.git'
    targetRevision: dev
    path: 'ovh/sg-db'
    directory:
      recurse: false
      include: '*.yaml'
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
