apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: penumbra-nodes
  namespace: karpenter
spec:
  amiFamily: AL2
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "rc-shared"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "rc-shared"
  instanceProfile: "KarpenterNodeInstanceProfile-rc-shared"
  amiSelectorTerms:
    - id: "ami-04bcf82576ac8eb1c"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        deleteOnTermination: true
  tags:
    karpenter.sh/discovery: "rc-shared"
  userData: |
    #!/bin/bash
    echo "Running custom userdata script for Penumbra nodes"
    # Optimize for blockchain workloads
    sysctl -w vm.max_map_count=262144
    sysctl -w vm.swappiness=1

---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  instanceProfile: "KarpenterNodeInstanceProfile-rc-shared"
  amiSelectorTerms:
    - id: "ami-04bcf82576ac8eb1c"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        volumeSize: 250Gi
        volumeType: gp3
  metadataOptions:
    httpEndpoint: enabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: rc-shared
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: rc-shared


---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: kubelet-custom
spec:
  amiFamily: AL2
  instanceProfile: "KarpenterNodeInstanceProfile-rc-shared"
  amiSelectorTerms:
    - id: "ami-04bcf82576ac8eb1c"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: rc-shared
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: rc-shared
  metadataOptions:
    httpEndpoint: enabled
    httpPutResponseHopLimit: 2
    httpTokens: optional
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 150Gi
        volumeType: gp3
        deleteOnTermination: true
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="BOUNDARY"

    --BOUNDARY
    Content-Type: text/x-shellscript; charset="us-ascii"

    #!/bin/bash
    echo "$(jq '.registryPullQPS=50|.registryBurst=100|.maxPods=250' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json

    --BOUNDARY--
